### ISSUE TITLE
Front-end to-do

### ISSUE THREAD

**Issue by hanbyul-here** [RMI-Climate-Intelligence/oci#6]
Starting this ticket to sort out to-dos on front-end in high level. 

OCI is going to have a lot more kinds of oil (~600). Existing pages, data processing code need to be updated accordingly. 

### Refactor code
 - [x]  Data processing code
   - Update dependencies / Get rid of dependencies that are not necessary/replacable.
 
- Application code
  - [x] Rewrite Backbone based code into React
    - Use DS's Seed Library  
  - [x] Update Styles following RMI new branding/  DS UI theme
    - font
    - color
  - [x] Get rid of unnecessary/replacable dependencies(ex.jQuery)
  - [x] Update D3 (v3 -> v6)
    - Update how D3 is used. (D3 will do more math and delegate most of DOM manipulations to React.) 
  
### New data related
- Data processing code
   - Check if the code can be scaled to handle 600 kinds of oils
   - Find spots to optimize data schema for application. 

- Application code
  - Design decision: How the new data should be incorporated into each page?
    - Total Emission page: This page needs to show all 600 hundred oil. 
      - Showing big picture vs Being able to find a specific oil? 
      - idea to show big picture / but still to offer detailed view: https://observablehq.com/@d3/focus-context
    - Analysis page: ?? not decided
      - What kind of design updates we need?  
    - Supply Chain page: Group oil by ${ ??? } and use it for this page.
      - What kind of design updates we need?  
  - Add Case study page
    - How would it look like? Where does this go on nav?  
  - Any update needed for other pages?
